### ISSUE TITLE
Page 180 - PEBCAC and Jammed Targets

### ISSUE THREAD

**Issue by lenaleciel** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#119]
Jammed characters can't "benefit from tech actions" which presumably includes PEBCAC which is a Quick Tech action. This detail of Jammed is often forgotten though, as the whole "can't attack or take reactions" thing is usually what people remember about it, and there are a few particularly notable tech actions that result in a Jammed PC that people may attempt to PEBCAC away.

Reminder text that Jammed characters can't benefit from tech actions might be helpful because of this.

**Comment by KaiTave** [comment]
If this is the designer's intent (that PEBCAC abides by Jammed's restriction on benefiting from tech actions) and reminder text is deemed worth including, the simplest way to do so would probably be along these lines, with bolding as follows:

"An **allied mech character** within line of sight and **SENSORS** quickly flash reboots at the system level. This ends all effects caused by **tech actions**, stops NHP cascades, and gives the target Immunity to all tech actions – hostile and allied – other than this one until the end of their next turn. This cannot be used on **Jammed** characters."

**Comment by Piezoelectric** [comment]
Book uses kai's wording
